### ISSUE TITLE
What does this library do that the default Markdig implementation doesn't do?

### ISSUE THREAD

**Issue by Shazwazza** [ilich/Markdig.Prism#4]
Hi,

(NOTE: This may be a very naive question 😄 ) 

I was using this library but realized that I was having issues with rendering XML code snippets since the encoding was coming out incorrectly (i.e. not encoded for HTML display). I disabled the .UsePrism() extension and realized that the output code was encoded correctly for HTML display and also still included the `language-{code}` class attributes.

Since the correct class/language attributes are already applied with the default Markdig implementation, I'm unsure why I need this library for Prism syntax highlighting to work since it seems to 'just work' out of the box. 

Is the main difference the encoding? If so, when is the case that you wouldn't want the code html encoded for html display?

**Comment by ilich** [comment]
Hi,

Sorry for the late reply. It was I while since I worked on this project. The extension is very simple: it adds https://prismjs.com/ support to markdown. If you disable the extension, your code will be rendered on the page, but won't be formatted. 

If you want to add custom language (Prism support dozens of languages), you can configure your custom Prism.js bundle on https://prismjs.com/download.html#themes=prism&languages=markup+css+clike+javascript page

**Comment by Shazwazza** [comment]
Hi thanks,

It could be possible that this lib was made before markdig automatically added css classes to the output? In any case, prism works just fine with the default markdig implementation because it automatically adds the css classes that prism supports for all code fences. 

I'll close this since it was just a question :)
